### ISSUE TITLE
Close the sidebar when an item gets clicked

### ISSUE THREAD

**Issue by JakeStaTeresa** [dnfloresc/bakery-website#1]
Hi @dnfloresc,

This is how you can close the sidebar when an item gets clicked. Hope this helps. Cheers! =D

https://github.com/dnfloresc/bakery-website/blob/f8cce074c7e2d2549148939d470265dfb0a55b5a/index.html#L152

```
const navigationItems = document.querySelectorAll('.nav-bar a');
navigationItems.forEach(i => i.addEventListener('click', function() {
    navBar.classList.remove("is-active");
}));
```

**Comment by iamdulce** [comment]
Thank you so much for your help, Jake!

You're great! 🙆🏻‍♀️ I'm going to apply it tomorrow and see how it goes!

I hope you're good and having a great weekend!
